# Generated by Django 4.2 on 2023-05-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_exercises'),
        ('main_app', '0002_workout_user'),
    ]

    operations = [
    ]
