# Generated by Django 4.2 on 2023-05-03 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_merge_0002_exercises_0002_workout_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='workout date')),
                ('track', models.CharField(choices=[('C', 'Cardio'), ('S', 'Strength'), ('Y', 'Yoga')], default='C', max_length=5)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.workout')),
            ],
        ),
    ]
