# Generated by Django 4.2 on 2023-05-04 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_workout_workout_type'),
        ('main_app', '0008_alter_exercises_yoga_flow'),
    ]

    operations = [
    ]
