# Generated by Django 4.2 on 2023-05-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.TextField(default='Workout', max_length=150)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
