# Generated by Django 4.2 on 2023-04-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'Cardio'), ('Y', 'Yoga'), ('S', 'Strength')], default='C', max_length=1)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
