# Generated by Django 4.2 on 2023-05-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_tracking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='sets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='yoga_flow',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
