# Generated by Django 4.2 on 2023-05-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_exercises_distance_alter_exercises_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='yoga_flow',
            field=models.CharField(blank=True, null=True),
        ),
    ]
